> ### **Assignment 2 - Numpy Array Operations** 



# 5 Interesting numpy functions.


### Some unique functions to make your array manipulations easier...

numpy is a python library for working with arrays, it is built using c so its faster than the in-built python functions for array manipulations. 
Here is a list of 5 interesting numpy functions: 

- numpy.linspace()
- numpy.tile()
- numpy.logical_and()
- numpy.argmax()
- numpy.fromiter()


Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [ ]:
import numpy as np

In [ ]:
# List of functions explained 
function1 = np.linspace 
function2 = np.tile
function3 = np.array_equal
function4 = np.argmax
function5 = np.fromiter

## Function 1 - np.linspace()

This function returns an array of *num* equally spaced values from *start* to *end* 

In [ ]:
# Example 1 - working 
v = np.linspace(0,10, num = 5)
print(v)


[ 0.   2.5  5.   7.5 10. ]


The above linspace function takes in **0** as **start point**, **10** as the **end point**(inclusive) and makes **5** equally spaced values from 0 to 10, </br> i.e 2.5 - 0 = 5 - 2.5 and so on

In [ ]:
# Example 2 - working
v = np.linspace(0,10,num=5,endpoint=False)
print(v)

[0. 2. 4. 6. 8.]


This is the same as the previous linspace however by specifying **endpoint = False** we create an equally spaced array from **0**(inclusive) to **10**(exclusive)

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
v = np.linspace(0,10, num = -5)
print(v)

ValueError: ignored

The linspace takes _num_ as a **positive** integer only, it cannot create -5 number of samples. This can be fixed by simply providing a positive value for _num_

This function is similiar to the np.arange() and is used to create an array from _start_ to _end_ interval, however instead of specifying the increment steps(like in np.arange) we can just specify the number of values we want and let the function calculate the required increment steps.

## Function 2 - np.tile()

This function creates a new array based on the array **A** we provide it. It repeates **A** given number of times in the specified axes.

In [ ]:
# Example 1 - working
v = [1,2,3,4,5]
v1 = np.tile(v, 2)
print(v1)

[1 2 3 4 5 1 2 3 4 5]


np.tile takes the array **v** and repeats is **2** times to create a new array.

In [ ]:
# Example 2 - working
v = [1,2,3,4,5]
v2 = np.tile(v, (2,1))
print(v2)

[[1 2 3 4 5]
 [1 2 3 4 5]]


The input array can be repeated not just in one dimesion, if the repetition parameter has a dimension greater then array A it promotes A to the dimensions of repitions parameter. Hence, here the input array get promoted to a 2-d array repeating the array twice along the row and once along the columns.

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
v = [1,2,3,4,5]
v3 = np.tile(v, [2,-1])
print(v3)

ValueError: ignored

Since there cannot be any array with negative dimensions, the above code breaks. This can be fixed by providing all positive dimensions

This function can be used to create custom arrays of any dimensions using pre-defined arrays.

## Function 3 - np.logical_and()

This function performs element-wise logical and operation

In [ ]:
# Example 1 - working
v1 = [1,1]
v2 = [1,0]

print(np.logical_and(v1,v2))

[ True False]


The functions performs logical and on the first element of both array and returns the boolean array of results

In [ ]:
# Example 2 - working
v1 = [[1, 0],[0,1]]
v2 = [1, 0]

print(np.logical_and(v1,v2))

[[ True False]
 [False False]]


It can also be performed on arrays of different dimensions as long as they can be broadcasted to a common shape

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
v1 = [1,1,0]
v2 = [1,0]

print(np.logical_and(v1,v2))

ValueError: ignored

Here we try to perform logical and on two different array with no comon shape to be broadcasted to, hence it breaks. This can be fixed by making sure that both the array have same dimensions or can be broadcasted to a common shape

This is a useful function when you want to create a boolean mask from two arrays

## Function 4 - np.argmax()

This method return the index of the max value in a given array along an axis


In [ ]:
# Example 1 - working
v = [[11,2,31,4,5],
     [1,12,1,14,15]]

print(np.argmax(v))

2


The function goes through each element and return the index of the highest value, if the index along which to search is not defined it, by default, return the index of the flattened array, hence the output is 2(i.e 31)

In [ ]:
# Example 2 - working
v = [[11,2,31,4,5],
     [1,12,1,14,15]]

print(np.argmax(v, axis=0))

[0 1 0 1 1]


Here the function does the same thing, but since the axis was defined as axis=0 it return the index value of the max value in each column

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
v = [[11,2,31,4,],
     ['1','2','3']]

print(np.argmax(v))

/usr/local/lib/python3.7/dist-packages/numpy/core/fromnumeric.py:43: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  result = getattr(asarray(obj), method)(*args, **kwds)


TypeError: ignored

The code breaks because it cannot compare strings to int, this is fixed by giving an array of all _int_ or _str_

Some closing comments about when to use this function.

## Function 5 - np.fromiter()

It creates a one dimensional array from an iterable object

In [ ]:
# Example 1 - working
def generate():
    for x in range(10):
        yield x
v = np.fromiter(generate(),dtype=float,)
print(v)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


The function takes in generate function as an iterable and for every return value from generate it adds it to the new array and sets the dtype as float

In [ ]:
# Example 2 - working 
v = [0,2,4,6]  
it = iter(v)  
z = np.fromiter(it, dtype = float)  
print(z)  


[0. 2. 4. 6.]


Here we create an iterable object from the v array using iter() which is then passed to the fromiter function to create a new array of type float

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
v = [0,2,4,6]  
it = iter(v)  
z = np.fromiter(it)  
print(z)  

TypeError: ignored

The code breaks because there is no declaration of the datatype, even though the array has only int/float we have to specify tha dtype to the fromiter function

This function is an alternative to np.array and basically does the same thing however since it generates a new array from an iterable object it is faster than np.array

## Conclusion

We have looked at 5 unique numpy functions that you probably didn't know about, these functions are mostly built for very specific scenarios and therefore are not used that much by an average user. </br>
You can discover more of such functions by visiting the official
[numpy docs](https://jovian.ai/outlink?url=https%3A%2F%2Fnumpy.org%2Fdoc%2Fstable%2Freference%2Froutines.html)

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* np.linspace : https://numpy.org/doc/stable/reference/generated/numpy.linspace.html
* np.tile : https://numpy.org/doc/stable/reference/generated/numpy.tile.html
* np.logical_and : https://numpy.org/doc/stable/reference/generated/numpy.logical_and.html
* np.argmax : https://numpy.org/doc/stable/reference/generated/numpy.argmax.html
* np.fromiter : https://numpy.org/doc/stable/reference/generated/numpy.fromiter.html